/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.SOCIOS DROP CONSTRAINT PLANOS_SOCIOS_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.SOCIOS;
DROP TABLE LABDATABASE.PLANOS;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.PLANOS_ID_PLANO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.PLANOS (
                ID_PLANO INTEGER NOT NULL,
                NOME VARCHAR2(100) NOT NULL,
                VALOR INTEGER NOT NULL,
                CONSTRAINT PLANOS_PK PRIMARY KEY (ID_PLANO)
);

CREATE TABLE LABDATABASE.SOCIOS (
                CPF VARCHAR2(14) NOT NULL,
                ID_PLANO INTEGER NOT NULL,
                ENDERECO VARCHAR2(150) NOT NULL,
                NOME VARCHAR2(100) NOT NULL,
                DATA_ASSOCIACAO DATE NOT NULL,
                DATA_DESATIVACAO DATE,
                TELEFONE VARCHAR2(11) NOT NULL,
                EMAIL VARCHAR2(100) NOT NULL,
                CONSTRAINT SOCIOS_PK PRIMARY KEY (CPF, ID_PLANO)
);

CREATE SEQUENCE LABDATABASE.PLANOS_ID_PLANO_SEQ;

/*Cria os relacionamentos*/

ALTER TABLE LABDATABASE.SOCIOS 
ADD CONSTRAINT PLANOS_SOCIOS_FK FOREIGN KEY (ID_PLANO)
REFERENCES LABDATABASE.PLANOS (ID_PLANO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.SOCIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.PLANOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;