/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.SOCIOS DROP CONSTRAINT PLANOS_SOCIOS_FK;
ALTER TABLE LABDATABASE.MENSALIDADE DROP CONSTRAINT PLANO_MENSALIDADE_FK;
ALTER TABLE LABDATABASE.MENSALIDADE DROP CONSTRAINT SOCIOS_MENSALIDADES_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.SOCIOS;
DROP TABLE LABDATABASE.PLANOS;
DROP TABLE LABDATABASE.MENSALIDADES;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.MENSALIDADES_ID_MENSALIDADE;
DROP SEQUENCE LABDATABASE.PLANOS_ID_PLANO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.PLANOS (
                ID_PLANO NUMBER NOT NULL,
                NOME VARCHAR2(100) NOT NULL,
                VALOR NUMBER NOT NULL,
                CONSTRAINT PLANOS_PK PRIMARY KEY (ID_PLANO)
);

CREATE TABLE LABDATABASE.SOCIOS (
                CPF VARCHAR2(14) NOT NULL,
                ID_PLANO NUMBER NOT NULL,
                ENDERECO VARCHAR2(150) NOT NULL,
                NOME VARCHAR2(100) NOT NULL,
                DATA_ASSOCIACAO DATE NOT NULL,
                DATA_DESATIVACAO DATE,
                TELEFONE VARCHAR2(11) NOT NULL,
                EMAIL VARCHAR2(100) NOT NULL,
                CONSTRAINT SOCIOS_PK PRIMARY KEY (CPF, ID_PLANO)
);


CREATE TABLE LABDATABASE.MENSALIDADES (
                ID_MENSALIDADE NUMBER NOT NULL,
                CPF VARCHAR2(14) NOT NULL,
                ID_PLANO NUMBER NOT NULL,
                DATA_CRIACAO DATE NOT NULL,
                DATA_VENCIMENTO DATE NOT NULL,
                DATA_PAGAMENTO DATE,
                VALOR_COBRANCA NUMBER NOT NULL,
                MULTA NUMBER,
                CONSTRAINT MENSALIDADES_PK PRIMARY KEY (ID_MENSALIDADE, CPF, ID_PLANO)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.MENSALIDADES_ID_MENSALIDADE;
CREATE SEQUENCE LABDATABASE.PLANOS_ID_PLANO_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.MENSALIDADES 
ADD CONSTRAINT PLANO_MENSALIDADE_FK FOREIGN KEY (ID_PLANO)
REFERENCES LABDATABASE.PLANOS (ID_PLANO)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.SOCIOS 
ADD CONSTRAINT PLANOS_SOCIOS_FK FOREIGN KEY (ID_PLANO)
REFERENCES LABDATABASE.PLANOS (ID_PLANO)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.MENSALIDADES 
ADD CONSTRAINT SOCIOS_MENSALIDADES_FK FOREIGN KEY (ID_PLANO, CPF)
REFERENCES LABDATABASE.SOCIOS (ID_PLANO, CPF)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.SOCIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.MENSALIDADES TO LABDATABASE;
GRANT ALL ON LABDATABASE.PLANOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;